import pygame

NEW_WAVE_EVENT_ID = pygame.USEREVENT + 501
ENEMY_SPAWN_INTERVAL_EVENT_ID = pygame.USEREVENT + 502
ONE_SECOND_EVENT_ID = pygame.USEREVENT + 503
TOWER_SHOOT_BASE_EVENT_ID = pygame.USEREVENT + 1000
